### ISSUE TITLE
[Query not Issue] [CatchPokemon] Hit Rate Limited

### ISSUE THREAD

**Issue by FreakySt0rm** [SwipeX/PokeMate#224]
Hi, just wondering what this is in the console logs. Does it prevent 100 poke balls being thrown to catch a 10CP Weadle? And is it configurable?

**Comment by FreakySt0rm** [comment]
Also getting this occassionally: [Update] Error - Hit Rate limiter.

Pokestops are being tagged and Pokemon caught, so everything seems to be working just fine. (Using the latest download and gradlew run)

**Comment by FreakySt0rm** [comment]
[HatchEgg] Hit rate limit
[HatchEgg] Hit rate limit

Also getting this. Is it the number of data-bursts being sent to the PMT server that's being limited?

**Comment by iDreamInBinary** [comment]
That means you are sending too many requests to the server (the server returned null to your request)

**Comment by ghost** [comment]
I am getting the same message. Not sure if it connected, but after I get a hit rate message, my user doesnt tag any pokestops.

**Comment by iDreamInBinary** [comment]
if it doesnt seem to do anything but spamming this message you are most probably softbanned

**Comment by alc4tras** [comment]
What use to run gradlew? never using it..

**Comment by ghost** [comment]
Definitely not soft banned, when I terminate and restart the bot, I hit pokestops again until i get the hit limiter message.

**Comment by iDreamInBinary** [comment]
@ksaiyanz then you probably just have to wait some longer for the bot to find new pokestops / pokemon
@alc4tras gradle. but you could also just use the latest release

**Comment by SippieCup** [comment]
https://github.com/SwipeX/PokeMate/issues/224#issuecomment-236376215

That is correct, there is another bugf I am about to push a fix for that addresses this case. I just want to make sure it actually works.

**Comment by ghost** [comment]
@SippieCup Awesome, thanks SippieCup.

**Comment by alc4tras** [comment]
@iDreamInBinary I mean what is its function? Sorry for my english..

**Comment by SippieCup** [comment]
This has been resolved, please move off topic conversations to slack or a new issue thread.

**Comment by zionism** [comment]
I just re-downloaded everything and i am still getting this query in my cmd log

**Comment by ghost** [comment]
I am also getting the same error. Using the newest release and re-inserted config info just to be thorough.

**Comment by jdmloki** [comment]
Yep, I get Hit Rate Limit as well, I tried to get a new API Key, that did not resolve the issue either.

**Comment by jinkawasaki333** [comment]
I still encounter this problem with the latest release - 0.3.0.
Also constantly giving me RemoteServerException.

**Comment by MDashK** [comment]
I can also comfirm these issues on my end.

**Comment by masterof123** [comment]
The bot often just sends various variations of "Hit Rate limit" while doing nothing else in the console mode. It can be very unclear to tell if the bot is actually working or not unless in GUI mode, especially if it only spams errors (I'm pretty sure it's still catching pokemon even though it isnt logging them, though).

**Comment by SippieCup** [comment]
Bot handles this perfectly. Its the Niantic server rejecting the bots request because it came in too fast. This is just a notification that it was hit.
