### ISSUE TITLE
Error Spammed - java.lang.NullPointerException

### ISSUE THREAD

**Issue by jdmloki** [SwipeX/PokeMate#267]
This error begins spamming in the console about 5 minutes in - with or without UI. 
If using the UI the map loses the red route lines.

The Bot loses the ability to tag pokestops and appears to stop moving, the console shows it try to catch pokemon still. However after the error spams awhile java crashes and the bot must be restarted.

**Comment by SippieCup** [comment]
Looking into this.

**Comment by SippieCup** [comment]
@jdmloki Can you compile from the newest commit and see if it is still occurring?

**Comment by SippieCup** [comment]
@jdmloki I posted a new release which should solve this issue.

**Comment by EiTeR94** [comment]
Still have the issue after arround 5-6min

![capture](https://cloud.githubusercontent.com/assets/20646280/17324654/dac8d986-58a7-11e6-92bb-f7c208cfed12.PNG)

**Comment by SippieCup** [comment]
Set `show=false`

JavaFX is just being annoying as usual.

**Comment by EiTeR94** [comment]
Ok :( but i like your GUI :p

**Comment by SippieCup** [comment]
Yeah, Going to have to rebuild it though. If you want to know fi its walking or not you can look at the Navigate text and see if its moving to different waypoints or not. Its cool to look at, but right now it needs to be rebuilt.

**Comment by EiTeR94** [comment]
Ok mate, thank

**Comment by jdmloki** [comment]
@SippieCup was working on rebuilding damn intellij was not cooperating lol.

**Comment by SippieCup** [comment]
New release + `show=false` fixes this. Closing thread. If another Null pointer error not related to the GUI comes up please create a new thread.
